// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umdlzksdeayjjrbuvrol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtZGx6a3NkZWF5ampyYnV2cm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTcxOTcsImV4cCI6MjA3MTQzMzE5N30.DSABD-2gbj1KH_hM9zmDcCBvGcXxRV-2k2wTauge7-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});